### ISSUE TITLE
VR enabled pictures

### ISSUE THREAD

**Issue by janrenz** [schul-cloud/edtrio#108]
https://developer.apple.com/arkit/gallery/

**Comment by FWirtz** [comment]
Seems like a cool project!
Can you give a few more details on how you see this work in edtr.io?
Would there be 3d images? Would the students be able to use the editor via something like a oculus as vr glasses?
Also, do you mean AR or VR?
I really can see this work in the context of schools, sounds like a clever way of showing things.
