### ISSUE TITLE
Can't start editor

### ISSUE THREAD

**Issue by adrianjost** [schul-cloud/edtrio#118]
I can't start the editor anymore, tested it with latest master and dev commits (30637183dbf14fbef9213166e629ada3cfb1ffcb , 780da19a5ac4176f8511e2f7799e8cbeaf5840a5)
![image](https://user-images.githubusercontent.com/22987140/49362869-58ef8700-f6e0-11e8-970a-d233ad137faa.png)
![image](https://user-images.githubusercontent.com/22987140/49362919-83d9db00-f6e0-11e8-9658-25cde6058aa6.png)

The latest working commit for me is: 11d50c4cbac4d5772cf2ef9837d751cb1734b323 this means that this commit is breaking it for me: 3fedaabe6244890574545aed8532a76fff33ba2a

Setup:
Native install via npm on a Windows 10

**Comment by Atyanar** [comment]
Closing this since this has been resolved.
