### ISSUE TITLE
yarn start error: "The new decorators proposal is not supported yet."

### ISSUE THREAD

**Issue by frogg** [schul-cloud/edtrio#62]
I tried to 'compile' your editor on my machine but I am running into an error:

What I did is:

- `npm install`
- `yarn start`

Result:

```
The new decorators proposal is not supported yet. You must pass the `"legacy": true` option to @babel/plugin-proposal-decorators (While processing: "/Users/frederik/Developer/edtrio/node_modules/@babel/plugin-proposal-decorators/lib/index.js")
```

Did you run into similar issues or know how to fix this?

**Comment by Trunken** [comment]
Hey @frogg,

this issue appears to be related to the babel-loader version and the decorator proposal babel plugin. I created a quick fix/babel-decorator branch where all decorators are removed. Please try it with a clean node_modules installation/repo folder. I had similar issues updating the packages. I will test it thoroughly later this day.

**Comment by frogg** [comment]
Hey Trunken!

Thanks for the quick follow-up and fix!
I was able to compile and run the editor now 🎉
