### ISSUE TITLE
Using copy and paste it possible to copy a section into a section

### ISSUE THREAD

**Issue by janrenz** [schul-cloud/edtrio#79]
<img width="827" alt="screenshot 2018-09-18 at 23 52 29" src="https://user-images.githubusercontent.com/224011/45718608-051fd800-bb9e-11e8-9694-d6879eceba8b.png">

**Comment by FWirtz** [comment]
this is probably related to the schema not being restrictive enough at that point. I'll try to fix that before I am gone.

**Comment by FWirtz** [comment]
closing in favor of #91
