### ISSUE TITLE
Make hidden section semi transparent while in editing mode

### ISSUE THREAD

**Issue by janrenz** [schul-cloud/edtrio#80]

**Comment by FWirtz** [comment]
![image](https://user-images.githubusercontent.com/6052785/45953445-661a3680-c00a-11e8-8fde-0d6a25016ede.png)
Added this.

I propose that we add some sort of visual notification though in addition to the eye icon.
Maybe a permanently shown tooltip above the eye that says "this section is hidden" or something like that @janrenz ?

**Comment by FWirtz** [comment]
added said feature like this
![image](https://user-images.githubusercontent.com/6052785/45957992-95cf3b80-c016-11e8-9ecf-785906fda660.png)
here: eb00e71b226b767d8816eeb3299bc806f2c91649
