### ISSUE TITLE
Geogebra folder should be in lower letters 

### ISSUE THREAD

**Issue by janrenz** [schul-cloud/edtrio#81]
Otherwise this may break on machinse with a files systems that repects small and large letters in names

**Comment by MrSerth** [comment]
Probably related to this issue, I was unable to start the server:

```
Failed to compile.

./src/Editor.jsx
Module not found: `[full path]/edtrio/src/plugins/geogebra/index.js` does not match the corresponding path on disk `GeoGebra`.
```

**Comment by FWirtz** [comment]
on it, will change that today
